### ISSUE TITLE
mat File is missing

### ISSUE THREAD

**Issue by mk8090** [codnjsqkr/FastAno_official#1]
I downloaded the dataset from the provided [link](http://www.svcl.ucsd.edu/projects/anomaly/dataset.htm) in the readme, but ped2.mat is missing. it is used [here](https://github.com/codnjsqkr/FastAno_official/blob/55b9a35d8c97696c3a935e5b3e9f173e0608ec1a/dataloader.py#L104). also the data folder structure does not match the one in the readme. @codnjsqkr.

**Comment by codnjsqkr** [comment]
Hi, you can download it from here: https://drive.google.com/drive/folders/1oJ5us7emy6p_h9DQsop5Cmz2wme8SeNC?usp=sharing
